### ISSUE TITLE
Settings panel

### ISSUE THREAD

**Issue by costomato** [Suyious/purrr.frontend#24]
A setting panel needs to be created ASAP, so that users can change their info anytime!

**Comment by Suyious** [comment]
See, before I assign you on this issue, I need to first have a final design ready for how the settings panel would look so that my idea of the application aligns with what you create. Also it would be better if I assign you on a more confined issue addressing a specific feature and not on a major feature all at once.

**Comment by HarshNarayanJha** [comment]
I understand. Let me know if you're done on either
