### ISSUE TITLE
Stop/Next chat button

### ISSUE THREAD

**Issue by costomato** [Suyious/purrr.frontend#9]
Add a button to stop chatting

**Comment by Suyious** [comment]
I am working on this issue and even though this feature is quite straight-forward, there are further implications that arise once this issue is addressed. The matching algorithm is currently very primitive. So once the user clicks next, he will be disconnected from the partner and will start looking for a new partner. In this scenario, it's possible that he reconnects with the same partner if the latter also tries to connect again at the same time. This is because the matching algorithm does not match the users randomly. Rather it just matches with the latest user that joined.
